install: Early update to the script
It doesn't work yet, but now is shaped closer to what is needed.

diff --git a/util/install b/util/install
--- a/util/install
+++ b/util/install
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 show_usage()
 {
@@ -10,12 +10,11 @@ Available options:
   -t PATH  copy data to PATH (e.g. /usr/local/share/syndre)
 
   -M       do not copy music
-  -d DEVICE read audio tracks from DEVICE (e.g. /dev/sr0)
   -l LANG  choose language LANG
 
   -h       print usage information
 
-Available languages: eng fre ger ita spa swe
+Available languages: ${LANGS}
 EOF
 }
 
@@ -29,7 +28,16 @@ OWN_TARGET="no"
 DEVICE=""
 SOURCE=""
 TARGET=""
+LANGS="eng fre ger ita spa swe"
 LANG="eng"
+
+GFX_VERSION="1.0.0.2"
+GFX_PACKAGE="syndre-gfx-1_0_0_2"
+GFX_PKG_MD5="944b13618593cf7659959745b338d0f4"
+
+SFX_VERSION="1.0.0.3"
+SFX_PACKAGE="syndre-sfx-1_0_0_3"
+SFX_PKG_MD5="802295bb0bea825a3772d1d120229d93"
 
 OPTS="f:t:Md:l:h"
 
@@ -58,27 +66,6 @@ while getopts "$OPTS" arg; do
       exit 1
   esac
 done
-
-check_music_tools()
-{
-  if [ "$WITH_MUSIC" = "no" ]; then
-    return 0
-  fi
-
-  CDPARANOIA=`which cdparanoia`
-  OGGENC=`which oggenc`
-
-  if [ -z "$CDPARANOIA" ] || [ -z "$OGGENC" ]; then
-    cat<<EOF >&2
-You don't have the tools needed to copy the music.  Please ensure that you
-have 'cdparanoia' and 'oggenc' (from vorbis-tools) in your path or run with
--M and try again.
-EOF
-    return 1
-  fi
-
-  return 0
-}
 
 check_source()
 {
@@ -122,27 +109,33 @@ check_target()
   return 0
 }
 
-copy_music()
+dl_package()
 {
-  if [ "$WITH_MUSIC" = "no" ]; then
-    return 0
+  local proj_nam=$1
+  local pkg_nam=$2
+  local pkg_ver=$3
+  local pkg_md5=$4
+
+  local real_md5=`md5sum "${pkg_nam}.zip" | cut -d " " -f1`
+  if [[ "x${real_md5}" != "x${pkg_md5}" ]]; then
+    wget "https://github.com/${proj_nam}/releases/download/${pkg_ver}/${pkg_nam}.zip" || return 1
   fi
 
-  install -v -d "$TARGET/music" || return 1
+  local real_md5=`md5sum "${pkg_nam}.zip" | cut -d " " -f1`
+  if [[ "x${real_md5}" != "x${pkg_md5}" ]]; then
+    printf 'Downloaded package MD5 mismatch: %s\n' "$pkg_nam" >&2
+    printf 'Expected md5sum: %s\n' "$pkg_md5" >&2
+    return 1
+  fi
 
-  for track_number in 1 2 3; do
-    local cd_number=$(($track_number+1))
-    local track_wav="$TARGET/music/track_$track_number.wav"
-    local track_ogg="$TARGET/music/track_$track_number.ogg"
-    if [ -z "$DEVICE" ]; then
-      "$CDPARANOIA" "$cd_number" "$track_wav" || return 1
-    else
-      "$CDPARANOIA" -d "$DEVICE" "$cd_number" "$track_wav" || return 1
-    fi
-    "$OGGENC" -b 192 "$track_wav" || return 1
-    rm -vf "$track_wav" || return 1
-    chmod 0644 "$track_ogg" || return 1
-  done
+  return 0
+}
+
+download_packages()
+{
+  dl_package "swfans/syndre-levels" "${LEVELS_PACKAGE}" "${LEVELS_VERSION}" "${LEVELS_PKG_MD5}" || return 1
+  dl_package "swfans/syndre-gfx" "${GFX_PACKAGE}" "${GFX_VERSION}" "${GFX_PKG_MD5}" || return 1
+  dl_package "swfans/syndre-sfx" "${SFX_PACKAGE}" "${SFX_VERSION}" "${SFX_PKG_MD5}" || return 1
 
   return 0
 }
@@ -160,6 +153,25 @@ install_file()
     return 1
   fi
 
+  install -v -T -m 0644 "$src" "$dst" || return 1
+
+  return 0
+}
+
+install_file_to()
+{
+  local fname="$1"
+  local dstdir="$2"
+
+  # Find the input file name ignoring case
+  local src=`find "$SOURCE" -ipath "$SOURCE/$fname"`
+  local fbase=`basename "$fname"`
+  local dst="$TARGET/$dstdir/$fbase"
+
+  if [ ! -n "$src" ]; then
+    printf 'File missing from your SOURCE: %s\n' "$fname" >&2
+    return 1
+  fi
 
   install -v -T -m 0644 "$src" "$dst" || return 1
 
@@ -177,78 +189,105 @@ install_dir()
   return 0
 }
 
-install_directory()
-{
-  local src="$1"
-  local dst="$2"
-
-  install -v -d "$dst" || return 1
-
-  find "$src" -mindepth 1 -maxdepth 1 -type f \
-    | while read file; do
-        local bn=`basename "$file"`
-	install -v -m 0644 "$file" "$dst/$bn" || return 1
-      done
-
-  find "$src" -mindepth 1 -maxdepth 1 -type d \
-    | while read subdir; do
-        local bn=`basename "$subdir"`
-	install_directory "$subdir" "$dst/$bn" || return 1
-      done
-
-  return 0
-}
-
 copy_data()
 {
   install_dir "data" || return 1
 
-  for fn in mouse-0 pointers; do
+  for fn in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 90 91 92 93 94 95 96 97 98 99; do
+    install_file "data/game${fn}.dat" || return 1
+  done
+
+  for fn in 01 02 03 04 05 06 07 08 09 10 11 12 13 15 16 17 18 19 20 21 31 32 34 35 37 38 39 40 41 43 50 51 52 53 54 55 56 57 58 60 61 62 63 64 65 66 67 70 71 72 73 80 81 82 90 91 92 93 94; do
+    install_file "data/map${fn}.dat" || return 1
+  done
+
+  for fn in  01  02  03  04  05  06  07  08  09  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50; do
+    install_file "data/miss${fn}.dat" || return 1
+  done
+
+  for fn in 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150; do
+    install_file "data/miss${fn}.dat" || return 1
+  done
+
+  for fn in 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250; do
+    install_file "data/miss${fn}.dat" || return 1
+  done
+
+  for fn in 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350; do
+    install_file "data/miss${fn}.dat" || return 1
+  done
+
+  for fn in 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450; do
+    install_file "data/miss${fn}.dat" || return 1
+  done
+
+  for fn in hpointer hspr-0 hspr-1; do
     install_file "data/${fn}.dat" || return 1
     install_file "data/${fn}.tab" || return 1
   done
 
-  for fn in mele-0 mfra-0 msta-0 nfra-0 nsta-0 tmap; do
-    install_file "data/${fn}.ani" || return 1
+  for fn in mfnt-0 mspr-0; do
+    install_file "data/${fn}.dat" || return 1
+    install_file "data/${fn}.tab" || return 1
   done
 
-  for fn in 0 1 2 3; do
-    install_file "data/pal${fn}.dat" || return 1
+  for fn in hpal01 hpal02 hpal03 hpal04 hpal05 hpalette; do
+    install_file "data/${fn}.dat" || return 1
   done
 
-  install_dir "data/equip" || return 1
-
-  for fn in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18; do
-    install_file "data/equip/net${fn}.fli" || return 1
+  for fn in intro.dat intro.xmi; do
+    install_file "data/${fn}" || return 1
   done
 
-
-  for dir in levels maps sound; do
-    install_directory "$SOURCE/$dir" "$TARGET/$dir" || return 1
+  for fn in isnds-0 isnds-1; do
+    install_file "data/${fn}.dat" || return 1
+    install_file "data/${fn}.tab" || return 1
   done
 
-  # Source lang dir (original game install files)
-  local sld="$SOURCE/language/$LANG"
+  for fn in gsound-0 sound-0 sound-1 ; do
+    install_file "data/${fn}.dat" || return 1
+    install_file "data/${fn}.tab" || return 1
+  done
 
-  install_dir "intro" || return 1
+  for fn in sample.ad sample.opl syngame.xmi gamedg.dll gamefm.dll; do
+    install_file "data/${fn}" || return 1
+  done
 
-  install -v -m 0644 "$sld/text.dat" "$TARGET/data" || return 1
-  install -v -m 0644 "$sld/intro.smk" "$TARGET/intro" || return 1
-  install -v -m 0644 "$sld/syn_ele.smk" "$TARGET/data" || return 1
-  install -v -m 0644 "$sld/chu_ele.smk" "$TARGET/data" || return 1
+  for fn in col01.dat hblk01.dat hele-0.ani hfnt01.dat hfra-0.ani hreq.dat hsta-0.ani mselect.pal; do
+    install_file "data/${fn}" || return 1
+  done
 
-  install -v -m 0644 "$sld/sound.dat" "$TARGET/sound" || return 1
+  for fn in mbrief mbrieout mconfout mconfup mconscr mdebrief mdeout mendlose mendwin mgamewin mlogos mlosa mlosaout mlosegam mmap mmapblk mmapout mminlogo mmulti mmultout moption moptout mresout mresrch mscrenup mselect mselout mtitle; do
+    install_file "data/${fn}.dat" || return 1
+  done
+
+  install_dir "sound" || return 1
 
   return 0
 }
 
-clean_data()
+extract_packages()
 {
-  rm -vrf "$TARGET/qdata/sound"
-  find "$TARGET/sound" -mindepth 1 -maxdepth 1 -type f ! -iname '*.dat' \
+  unzip -o "${GFX_PACKAGE}.zip" -d "${TARGET}" || return 1
+  find "$TARGET/syndre/data" -mindepth 1 -maxdepth 1 -type f -iname '*.*' \
     | while read file; do
-	rm -vf "$file"
+        mv -vn "$file" -t "${TARGET}/data" || return 1
       done
+  for dirn in $(echo ${LANGS}); do
+    find "$TARGET/syndre/language/${dirn}" -mindepth 1 -maxdepth 1 -type f -iname '*.*' \
+      | while read file; do
+          mv -vn "$file" -t "${TARGET}/language/${dirn}" || return 1
+        done
+  done
+  rm -rf "${TARGET}/syndre" || return 1
+
+  unzip -o "${SFX_PACKAGE}.zip" -d "${TARGET}" || return 1
+  find "$TARGET/syndre/sound" -mindepth 1 -maxdepth 1 -type f -iname '*.dat' \
+    | while read file; do
+        mv -vn "$file" -t "${TARGET}/sound" || return 1
+      done
+  rm -rf "${TARGET}/syndre" || return 1
+
   return 0
 }
 
@@ -287,13 +326,6 @@ create_config_ini()
 CD="D:\\GAME\\"
 InstallDrive="C:\\"
 Language="$LANG_NAME"
-Intro="Max"
-Anims="Max"
-Sound="Max"
-Levels="Max"
-Data="Max"
-Maps="Max"
-DOS="Max"
 EOF
   [ $? -eq 0 ] || return 1
   return 0
@@ -310,12 +342,11 @@ error()
 }
 
 check_source || error
-check_music_tools || error
 check_language || error
 check_target || error
-copy_music || error
+download_packages || error
 copy_data || error
-clean_data || error
+extract_packages || error
 create_config_ini || error
 
 echo "Data successfully installed."
